language: go
go: 1.12.x
dist: trusty

sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libcairo2-dev -y
  - sudo apt-get install tree -y

jobs:
  include:
    - stage: Tests
      name: Unit tests
      script:
        - env
        - mkdir -p /home/travis/gopath/src/github.com/bookingcom/carbonapi && rsync -a . ../../bookingcom/carbonapi/
        - cd ../../bookingcom/carbonapi/
        - make check
        - make all
          #after_success: bash <(curl -s https://codecov.io/bash)
    - name: Integration tests
      script: tests/system_test.sh

