language: go
go: 1.12.x
dist: trusty

sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libcairo2-dev -y
  - mkdir /home/travis/gopath/src/github.com/bookingcom
  - rsync -av /home/travis/gopath/src/github.com/kostty/carbonapi /home/travis/gopath/src/github.com/bookingcom/
  - cd /home/travis/gopath/src/github.com/bookingcom/carbonapi

jobs:
  include:
    - stage: Tests
      name: Unit tests
      script: make all check
      after_success: bash <(curl -s https://codecov.io/bash)
    - name: Integration tests
      script: tests/system_test.sh

